name: Java CI with Gradle and Docker (Multi-Module)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21 # Java 21 설정
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle' # 빌드 속도 향상을 위한 캐싱

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Querydsl 빌드 시 필요한 Q클래스 생성을 포함한 전체 빌드
    - name: Build with Gradle
      run: ./gradlew clean :web:build -x test # 실행 모듈만 빌드

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        # 멀티 모듈은 빌드된 jar 위치를 정확히 지정해야 함
        file: ./web/Dockerfile 
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-store-service:latest
